AkanshaBookReadingEventDP/BookReadingEvent.WebMVC/Controllers/BookReadingEventController.cs
using BookReadingEvent.WebMVC.Models;
using BusinessLogicLayer_BLL_.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer_BLL_.DataTransferObjects;
using BookReadingEvent.Domain.InterfaceRepository;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using FacadePattern.FacadeFactoryInterface;
using FacadePattern.FacadeInteface;
using BookReadingEvent.WebMVC.Filter;

namespace BookReadingEvent.WebMVC.Controllers
{
    [ExceptionHandlerViaLogging]
    public class BookReadingEventController : Controller
    {
       
        private readonly IFacadeFactory _facadeFacatory;
        private readonly IFacade _facade;
        private readonly IUserService _userService;
        public BookReadingEventController(IFacadeFactory facadeFacatory, IFacade facade, IUserService userService)
        {
            _facadeFacatory = facadeFacatory;
            _facade = facade;
            _userService = userService;
        }

        [Authorize]
        
        [Route("CreateEvent")]
        
        public ViewResult CreateEvent()
        { 
            return View();
        }

        [Authorize]
        [Route("CreateEvent")]
        [HttpPost]
        public async Task<IActionResult> CreateEvent(EventViewModel eventModel)
        {
            if (ModelState.IsValid)
            {
                var newEvent = new EventDTO()                
                {
                    Id = eventModel.Id,
                    Title = eventModel.Title,
                    Date = eventModel.Date,
                    StartTime = eventModel.StartTime,
                    Location = eventModel.Location,
                    Description = eventModel.Description,
                    OtherDetails=eventModel.OtherDetails,
                    Duration = eventModel.Duration,
                    Organiser = eventModel.Organiser,
                    EventType = eventModel.EventType,
                    Invitees = eventModel.Invitees,
                    CreatedBy = _userService.GetUserID()
                };
              
               var result = await _facade.CreateEvent(newEvent);
                if (result > 0)
                {
                    return RedirectToAction(nameof(CreateEvent));
                }
               
            }
            return View();

        }
        
        
        public async Task<IActionResult> EventDetails(int id)
        {         
            //Model Mapping
            EventViewModel data = new EventViewModel();
            var eventModelDTO = await _facade.EventDetails(id);          
            var config = new MapperConfiguration(cfg => cfg.CreateMap<EventDTO, EventViewModel>());
            var mapper = config.CreateMapper();
            data = mapper.Map<EventDTO, EventViewModel>(eventModelDTO);
           
            //Comment Mapping
            List<CommentViewModel> AllComments = new List<CommentViewModel>();
            var AllCommentsDTO = await _facade.GetAllComments(id);
            var config1 = new MapperConfiguration(cfg => cfg.CreateMap<CommentDTO, CommentViewModel>());
            var mapper1 = config1.CreateMapper();
            AllComments = mapper1.Map<List<CommentDTO>, List<CommentViewModel>>(AllCommentsDTO);

            data.Comments = AllComments;
            //After adding comment check data is null or not
            if (data == null)
            {
                return RedirectToAction("EventDetails");
            }
            return View(data);
            


        }
        
        [Authorize]
        public async Task<ActionResult> MyEvents()
        {
            var createdBy = _userService.GetUserID();
           
            List<EventDTO> EventListDTO = await _facade.MyEvents(createdBy);

            var config = new MapperConfiguration(cfg => cfg.CreateMap<EventDTO, EventViewModel>());
            var mapper = config.CreateMapper();
            List<EventViewModel> myEvents = mapper.Map<List<EventDTO>, List<EventViewModel>>(EventListDTO);
            myEvents.Reverse();
            return View("MyEvents", myEvents);
        }

        [Authorize]
        public async Task<ViewResult> EditEvent(int id, bool isSuccess = false)
        {
           // var data = await _eventService.EventDetailsById(id);
            EventViewModel data = new EventViewModel();
            var eventModelDTO = await _facade.EventDetails(id);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<EventDTO, EventViewModel>());
            var mapper = config.CreateMapper();
            data = mapper.Map<EventDTO, EventViewModel>(eventModelDTO);

            ViewBag.IsSuccess = isSuccess;
            return View(data);
        }

        /// <summary>
        /// Controller used to Edit the Events By using event id
        /// </summary>
        /// <param name="bookmodel"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditEvent(EventViewModel eventModel, int id)
        {
            if (ModelState.IsValid)
            {
                var editEvent = new EventDTO()
                {
                    Id = eventModel.Id,
                    Title = eventModel.Title,
                    Date = eventModel.Date,
                    StartTime = eventModel.StartTime,
                    Location = eventModel.Location,
                    Description = eventModel.Description,
                    OtherDetails = eventModel.OtherDetails,
                    Duration = eventModel.Duration,
                    Organiser = eventModel.Organiser,
                    EventType = eventModel.EventType,
                    Invitees = eventModel.Invitees,
                    CreatedBy = _userService.GetUserID()
                };

                var result = await _facade.EditEvent(editEvent,id);
                if (result > 0)
                {
                    return RedirectToAction(nameof(editEvent), new { isSuccess = true });
                }

            }
            return View();

        }
        [Authorize]
        [Route("EventsInvitedTo")]
        public async Task<ViewResult> EventsInvitedTo()
        {
            List<EventViewModel> eventListModel = new List<EventViewModel>();
            var eventList = await _facade.GetAllEvents();
            var config = new MapperConfiguration(cfg => cfg.CreateMap<EventDTO, EventViewModel>());
            var mapper = config.CreateMapper();
            eventListModel = mapper.Map<List<EventDTO>, List<EventViewModel>>(eventList);

            return View(eventListModel);
           
        }
    }
}

AkanshaBookReadingEventDP/BookReadingEvent.WebMVC/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<BookReadingEvent.Domain.Entities.ApplicationUser> _loginManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventsApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white-50" asp-action="Index" asp-controller="Home">BookEvents</a>
                <form class="d-flex">
                    @if (_loginManager.IsSignedIn(User))
                    {
                        <a asp-controller="BookReadingEvent" asp-action="MyEvents" class="mr-3 btn btn-light">My Events</a>
                        <a asp-controller="BookReadingEvent" asp-action="EventsInvitedTo" class="mr-3 btn btn-light">My Invites</a>
                        <a asp-controller="BookReadingEvent" asp-action="CreateEvent" class="mr-3 btn btn-light">Create New Event</a>
                        <a asp-controller="Account" asp-action="Logout" class="btn btn-light">Logout</a>
                    }
                    else
                    {
                        <a href="https://helpdesk.nagarro.com" class="mr-3 btn btn-light">Customer Support</a>
                        <a asp-controller="Account" asp-action="Register" class="mr-3 btn btn-light">Signup</a>
                        <a asp-controller="Account" asp-action="Login" class="btn btn-light">Login</a>
                    }
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - EventsApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>